net-im/decent-im: drop inherit eutils
Because:

ERROR: net-im/decent-im-9999::decent-im failed (depend phase):
eutils.eclass could not be found by inherit()